config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get :destroyAll
    end
  end

  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
end
 

  def destroyAll
    User.destroy_all

    respond_to do |format|
      format.html { redirect_to users_url, notice: "All Users was successfully destroyed." }
      format.json { head :no_content }
  end
end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :phone, :telegram)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'UserApp', root_path, class:"navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
         <%= link_to 'Users', users_path, class:"nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to " New user", new_user_path , class:"dropdown-item bi bi-person-plus"%>
          <div class="dropdown-divider"></div>
          <%= link_to " Delete All Users",'users/0/destroyAll', class:"dropdown-item bi bi-trash" %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/home/index.html.erb
<h1>UserApp</h1>
Some text

app/views/layouts/_alerts.html.erb
<br/>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
 <%= notice%>
  <button type="button" class="close" data-dismiss="alert" aria-label="close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TestApp</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css'> 
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
  <%= render 'home/header' %>
    <div class="container">
    
      <% if notice%>
        <%= render 'layouts/alerts'%>
      <% end %>

      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script></body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message class:"alert alert-success"%></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-sm-6">
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, class:"form-control" %>
  </div>

  <div class="form-group col-sm-6">
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class:"form-control"  %>
  </div>

  <div class="form-group col-sm-6">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class:"form-control"  %>
  </div>

  <div class="form-group col-sm-6">
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, class:"form-control"  %>
  </div>

  <div class="form-group col-sm-6">
    <%= form.label :telegram, style: "display: block" %>
    <%= form.text_field :telegram, class:"form-control"  %>
  </div>

  <div class="paddingLeft">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
<div>
 
    <h1><%= user.first_name %> <%= user.last_name %></h1>
    
    <p>
    <label>E-mail:</label>
    <%= user.email %>
     </p>

    <p>
        <label>Phone:</label>
        <%= user.phone %>
    </p>
    <p>
        <label>Telegram:</label>
        <%= user.telegram %>
    </p>

 </div>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div class="paddingLeft">
  <%= link_to " Show this user", @user, class:"btn btn-info bi bi-eye"%>
  <%= link_to "Back to users", users_path, class:"btn btn-secondary" %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>


<%= link_to " New user", new_user_path , class:"btn btn-outline-success bi bi-person-plus"%>

<div id="users">
<p></p>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>E-mail</th>
      <th>Phone</th>
      <th>Telegram</th>
      <th></th>
    </tr>
  </thead>
  <tbody>

<% @users.each do |user| %>
     <tr id="<%= dom_id user %>">

    <td class="align-middle"><%= user.first_name %></td>

    <td class="align-middle"><%= user.last_name %></td>

    <td class="align-middle"><%= user.email %></td>

    <td class="align-middle"><%= user.phone %></td>

    <td class="align-middle"><%= user.telegram %></td>

    <td class="align-middle" style="float: left; width: 100%;">
    <%= link_to " View", user , class:"btn btn-primary bi bi-eye"%>
    <%= link_to " Edit", edit_user_path(user), class:"btn btn-secondary bi bi-pen"%>
    <%#<%= link_to " Delete", destroy_user_path(user) , class:"btn btn-danger bi bi-trash"%>
    <%= button_to "Delete", user, method: :delete, class:"btn btn-danger bi bi-trash", form_class:"deleteForm" %>
    </td>
    </p>
</tr>
  <% end %>

  </tbody>
</table>

  
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div class="paddingLeft">
  <%= link_to "Back to users", users_path, class:"btn btn-secondary" %>
</div>

app/views/users/show.html.erb
<%= render @user%>
<div>
  <%= link_to " Edit this user", edit_user_path(@user), class:"btn btn-secondary bi bi-pen" %>
  <br/>
  <br/>
  <%= link_to "Back to users", users_path, class:"btn btn-secondary" %>
  <%= button_to " Destroy this user", @user, method: :delete, class:"btn btn-danger bi bi-trash", form_class:"deleteForm" %>
</div>